version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - nvm install 17.9.1 # Rolling back to Node.js v17.9.1
      - nvm use 17.9.1
      - npm install -g yarn # Still gotta have my yarn!
      - yarn install --ignore-engines # This is the game-changer
  build:
    commands:
      - echo Packaging JAR file...
      - java -version
      - nvm use 17.9.1
      - yarn run build
      - mvn clean package -Pprod
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/jhiptest.jar
  discard-paths: yes
