version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
  pre_build:
    commands:
      - npm install -g yarn # Still gotta have my yarn!
      - yarn install --ignore-engines # This is the game-changer
  build:
    commands:
      - echo Packaging JAR file...
      - java -version
      - yarn run build
      - mvn clean package -Pprod
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/jhiptest.jar
  discard-paths: yes
